services:
  caddy:
    image: caddy:alpine
    container_name: apollon2-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - shared-network

  webapp:
    build:
      context: ..
      dockerfile: ./standalone/webapp/Dockerfile
      args:
        VITE_BACKEND_URL_WSS: "wss://apollon2.aet.cit.tum.de/ws"
        VITE_BACKEND_URL: "https://apollon2.aet.cit.tum.de"
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - shared-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  server:
    build:
      context: ..
      dockerfile: ./standalone/server/Dockerfile
    expose:
      - "8000"
      - "4444"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - WSSPORT=4444
      - FRONTEND_URL=https://apollon2.aet.cit.tum.de
      - MONGO_URI=mongodb://db:27017/apollon2DB
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - shared-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - shared-network
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  dbdata:

networks:
  shared-network:
    name: shared-network
    driver: bridge
