services:
  webapp:
    build:
      context: ..
      dockerfile: ./standalone/webapp/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    environment:
      - APP_HOSTNAME=localhost
      - VITE_BACKEND_URL=http://localhost:8000
      - VITE_BACKEND_URL_WSS=ws://localhost:4444/ws
    networks:
      - shared-network

  server:
    build:
      context: ..
      dockerfile: ./standalone/server/Dockerfile
    ports:
      - "8000:8000"
      - "4444:4444"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - WSSPORT=4444
      - FRONTEND_URL=http://localhost:5173
      - MONGO_URI=mongodb://db:27017/apollon2DB
    depends_on:
      - db
    networks:
      - shared-network

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - shared-network

volumes:
  dbdata:

networks:
  shared-network:
    driver: bridge
