name: Build and Push Docker Image

on: # Adjust the triggers, conditions, etc. to your needs, see examples below
  pull_request:
  push:
    branches: [main]

jobs:
  # You can also build and push multiple images in parallel using a matrix (see examples)
  build-and-push-workflow:
    uses: ls1intum/.github/.github/workflows/build-and-push.yml@main
    with:
      image-name: ls1intum/Apollon2/apollon_reenginerring
      docker-file: Dockerfile 
    secrets: inherit