name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        description: "Image tag to deploy (default: pr-<number> if PR exists, latest for default branch)"
      
jobs:  
  deploy-webapp:
    uses: ls1intum/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: Production
      docker-compose-file: "./docker/compose.webapp.yml"
      main-image-name: ghcr.io/ls1intum/apollon2/apollon-webapp
      image-tag: ${{ inputs.image-tag }}
      #deployment-base-path: "/opt/apollon2/webapp"
    secrets: inherit

  deploy-server:
    uses: ls1intum/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: Production
      docker-compose-file: "./docker/compose.server.yml"
      main-image-name: ghcr.io/ls1intum/apollon2/apollon-server
      image-tag: ${{ inputs.image-tag }}
      #deployment-base-path: "/opt/apollon2/server"
    secrets: inherit

  deploy-proxy:
    uses: ls1intum/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: Production
      docker-compose-file: "./docker/compose.proxy.yml"
      # We just keep the main-image-name and image-tag as placeholders
      main-image-name: caddy
      image-tag: latest
      #deployment-base-path: "/opt/apollon2/proxy"
    secrets: inherit
  